---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: apic
  connection: local
  gather_facts: False
  
  
  tasks:
    - name: Add a new VLAN pool
      cisco.aci.aci_vlan_pool:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        use_ssl: true
        validate_certs: False
        pool: production
        pool_allocation_mode: static
        description: Production VLANs
