---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: 192.168.0.200
  connection: local
  gather_facts: False
  

  tasks:
    - name: Creation Tenant a partir d'un ficher variable 
      cisco.aci.aci_tenant:
        host: 192.168.0.200
        username: admin
        password: cisco1234
        state: "present"
        use_ssl: true
        validate_certs: False
        tenant: test111
        description: "Created With Ansible"
