---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: 192.168.0.200
  connection: local
  gather_facts: False
  

    - name: ENSURE TENANT VRF EXISTS
      aci_vrf:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        use_ssl: true
        validate_certs: False
        tenant: "{{ tenant }}"
        vrf: "{{ vrf }}"
        description: "VRF Created Using Ansible"

    - name: Add a new VLAN pool
      cisco.aci.aci_vlan_pool:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        use_ssl: true
        validate_certs: False
        pool: production
        pool_allocation_mode: static
        description: Production VLANs
